### ISSUE TITLE
运行 make migrate 报错

### ISSUE THREAD

**Issue by liujieking** [CyanAsterisk/FreeCar#103]
运行 make migrate 失败，报错如下：

go run server/cmd/auth/model/migrate/main.go
stat server/cmd/auth/model/migrate/main.go: no such file or directory
make: *** [migrate] Error 1

Process finished with exit code 2

**Comment by L2ncE** [comment]
你好您是1.1版本吗，我刚才测试了一下1.1版本是没有问题的，会不会的路径的问题？或者可以直接到 server/cmd/auth/model/migrate 下手动运行 main.go。
我们会在最近更新新版本，无需手动 migrate，会自动建表。
感谢关注与 issue~

**Comment by L2ncE** [comment]
看样子原因可能是你使用的是dev版本，dev版本还在开发中，请使用release的正式版本

**Comment by liujieking** [comment]
是的，谢谢
