### ISSUE TITLE
运行 make api 退出了

### ISSUE THREAD

**Issue by liujieking** [CyanAsterisk/FreeCar#110]
╭─   /src/FreeCar-0.1.1                                                                                                                                                                        15:39    192.168.3.5 
╰>>> make api
go run ./server/cmd/api
exit status 1
make: *** [api] Error 1

如上：运行make api以后提示1个错误，没有详细的错误日志信息了，排查不到问题。

**Comment by L2ncE** [comment]
通常这种情况都是环境问题，是不是Nacos没有配置呢

**Comment by liujieking** [comment]
非常感谢，我配置了，麻烦帮忙看下
![111](https://user-images.githubusercontent.com/7564541/227461277-33265d62-a6d4-4d8d-95e2-feefd74e6e71.png)
![222](https://user-images.githubusercontent.com/7564541/227461315-027628a1-2101-4944-b924-d21da4bdc007.png)

**Comment by L2ncE** [comment]
> 非常感谢，我配置了，麻烦帮忙看下 ![111](https://user-images.githubusercontent.com/7564541/227461277-33265d62-a6d4-4d8d-95e2-feefd74e6e71.png) ![222](https://user-images.githubusercontent.com/7564541/227461315-027628a1-2101-4944-b924-d21da4bdc007.png)

应该没有问题，你再试试呢

**Comment by liujieking** [comment]
试了很多次，还是不行，没有错误日志，框架我不太熟悉，如果方便的话请加我一下飞书跟您请教学习一下，谢谢。
刘杰申请添加你为联系人，点击链接处理 https://www.feishu.cn/invitation/page/add_contact/?token=fd0p4055-aa50-4eaf-a986-914fcf86e70c&amp;unique_id=68W4CwDSlEFtLheiGpFb8w==

**Comment by liujieking** [comment]
跟我用的golang的版本有关吗，
go version go1.20.1 darwin/amd64
还有就是个别一两个包升级了，github.com/bytedance/sonic@v1.7.0

**Comment by L2ncE** [comment]
加你飞书了 目前只保证1.18~1.19没问题
