### ISSUE TITLE
文档api注解地址404

### ISSUE THREAD

**Issue by cuteLittleDevil** [CyanAsterisk/FreeCar#132]
**Describe the bug**

文档中文 api注解地址 显示404
https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/toolkit/#%E6%94%AF%E6%8C%81%E7%9A%84-api-%E6%B3%A8%E8%A7%A3

1. 文档地址 https://github.com/CyanAsterisk/FreeCar/blob/main/README_zh.md
2. 点击开发指南 IDL api注解 显示404

显示正确的地址
如 https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/usage/annotation/

![image](https://user-images.githubusercontent.com/38343763/231955428-f5286ac7-ec8a-41e6-af7a-978f9885aeae.png)

![image](https://user-images.githubusercontent.com/38343763/231955300-a425dc6a-c612-4afd-a124-0de6a2424b20.png)

**Comment by L2ncE** [comment]
感谢 issue，我们会尽快改正❤️

**Comment by L2ncE** [comment]
Done
