### ISSUE TITLE
请问 make start 以后怎么配置 Consul 呢？

### ISSUE THREAD

**Issue by FrazierLei** [CyanAsterisk/FreeCar#134]
`make api` 会报这个错：

> {"level":"info","msg":"Config Info: {127.0.0.1 8510 freecar/api_srv}","time":"2023-04-21T22:29:43+08:00"}
> {"level":"fatal","msg":"consul kv failed: Get \"http://127.0.0.1:8510/v1/kv/freecar/api_srv\": dial tcp 127.0.0.1:8510: connect: connection refused","time":"2023-04-21T22:29:43+08:00"}
> exit status 1
> make: *** [api] Error 1

Consul 界面是这样的，怎么把其他端口注册上去呢？还是新手
<img width="675" alt="Snipaste_2023-04-21_22-39-05" src="https://user-images.githubusercontent.com/43394641/233664320-5fe50585-c865-44f4-ad3f-5479442c4034.png">

**Comment by Nihilism0** [comment]
点击Key/Value并点击右边的Create
<img width="290" alt="image" src="https://user-images.githubusercontent.com/114405451/233690687-016e3dbb-7350-41dd-be02-98452d73bd7b.png">
输入需要的配置信息
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/114405451/233691101-dbaa0ffb-4e01-44aa-bfe5-a1f0d9fa9e09.png">

具体配置信息，[详见](https://github.com/CyanAsterisk/FreeCar/blob/dev/docs/CONSUL_CONFIG.md)

**Comment by FrazierLei** [comment]
感谢您的耐心回复！
刚刚这么操作了一下遇到这样的报错信息，
```
$ make api
go run ./server/cmd/api
{"level":"info","msg":"Config Info: {127.0.0.1 8500 freecar/api_srv}","time":"2023-04-22T01:01:38+08:00"}
{"level":"fatal","msg":"tls failedtls: failed to find any PEM data in key input","time":"2023-04-22T01:01:38+08:00"}
exit status 1
make: *** [api] Error 1
```
是需要预先配置一下证书信息吗？
我把 `main.go` 中和 tlsCfg 相关的代码注释掉以后可以运行了😂

**Comment by Nihilism0** [comment]
> 

是的
